Build custom AMI for the DevSpaces (arm64, updated)
trilogy-group/amazon-eks-ami pull request #2
Opened 2021-07-26 07:41 UTC by amulobaev

2021-07-26 12:59 UTC, pavan-tri requested changes

2021-07-26 12:59 UTC, pavan-tri commented on scripts/install_additional_components.sh
> +wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-arm64.tar.gz -O /tmp/crictl-linux-arm64.tar.gz
Can we have a "IF" condition for ARM vs X86 and install appropriately

2021-07-27 07:37 UTC, amulobaev commented on scripts/install_additional_components.sh
> +wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-arm64.tar.gz -O /tmp/crictl-linux-arm64.tar.gz
Fixed

2021-07-27 07:43 UTC, pavan-tri approved these changes
LGTM

2021-07-27 07:48 UTC, merged